import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { resolve } from 'path'

// Load .env.local manually since Next.js env isn't available in scripts
function loadEnv() {
  try {
    const envFile = readFileSync(resolve(process.cwd(), '.env.local'), 'utf-8')
    for (const line of envFile.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const idx = trimmed.indexOf('=')
      if (idx === -1) continue
      const key = trimmed.slice(0, idx).trim()
      const value = trimmed.slice(idx + 1).trim()
      if (!process.env[key]) process.env[key] = value
    }
  } catch {
    console.warn('Could not load .env.local — ensure env vars are set')
  }
}

loadEnv()

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

type FoodSeed = {
  name_english: string
  name_hindi?: string | null
  aliases?: string[]
  category: string
  cuisine_tag?: string | null
  serving_unit: string
  serving_size_grams?: number | null
  calories?: number | null
  protein_g?: number | null
  carbs_g?: number | null
  fiber_g?: number | null
  fat_g?: number | null
  iron_mg?: number | null
  calcium_mg?: number | null
  folate_mcg?: number | null
  b12_mcg?: number | null
  vitamin_d_iu?: number | null
  omega3_mg?: number | null
  dha_mg?: number | null
  choline_mg?: number | null
  magnesium_mg?: number | null
  potassium_mg?: number | null
  sodium_mg?: number | null
  hydration_per_serving_ml?: number | null
  pregnancy_safe?: 'safe' | 'avoid' | 'moderate'
  pregnancy_notes?: string | null
  trimester_notes?: Record<string, string>
  is_verified?: boolean
}

const foodItems: FoodSeed[] = [
  // ── GRAINS & BREAKFAST ────────────────────────────────────────────────────
  {
    name_english: 'Idli',
    name_hindi: 'इडली',
    aliases: ['idly', 'rice cake'],
    category: 'grain',
    cuisine_tag: 'south-indian',
    serving_unit: '1 piece',
    serving_size_grams: 50,
    calories: 39,
    protein_g: 1.9,
    carbs_g: 8,
    iron_mg: 0.5,
    calcium_mg: 7,
    folate_mcg: 8,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Fermented — great probiotic, easy to digest in T1 nausea',
    trimester_notes: { T1: 'Ideal during nausea — light and easily digestible' },
    is_verified: true,
  },
  {
    name_english: 'Dosa plain',
    name_hindi: 'सादा डोसा',
    aliases: ['plain dosa', 'dosa'],
    category: 'grain',
    cuisine_tag: 'south-indian',
    serving_unit: '1 medium',
    serving_size_grams: 70,
    calories: 112,
    protein_g: 2.4,
    carbs_g: 21,
    iron_mg: 0.8,
    calcium_mg: 8,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Poha',
    name_hindi: 'पोहा',
    aliases: ['flattened rice', 'chivda', 'beaten rice'],
    category: 'grain',
    cuisine_tag: 'maharashtrian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 165,
    protein_g: 3.5,
    carbs_g: 32,
    iron_mg: 2.1,
    calcium_mg: 12,
    folate_mcg: 15,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Iron-rich grain. Add lemon juice to boost iron absorption',
    is_verified: true,
  },
  {
    name_english: 'Upma',
    name_hindi: 'उपमा',
    aliases: ['rava upma', 'semolina upma'],
    category: 'grain',
    cuisine_tag: 'south-indian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 195,
    protein_g: 4,
    carbs_g: 30,
    iron_mg: 1.5,
    calcium_mg: 15,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Paratha plain',
    name_hindi: 'सादा पराठा',
    aliases: ['plain paratha', 'paratha'],
    category: 'grain',
    cuisine_tag: 'north-indian',
    serving_unit: '1 medium',
    serving_size_grams: 60,
    calories: 185,
    protein_g: 3.8,
    carbs_g: 28,
    fat_g: 7,
    iron_mg: 1.2,
    calcium_mg: 20,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Aloo paratha',
    name_hindi: 'आलू पराठा',
    aliases: ['potato paratha', 'stuffed paratha'],
    category: 'grain',
    cuisine_tag: 'punjabi',
    serving_unit: '1 piece',
    serving_size_grams: 100,
    calories: 280,
    protein_g: 5,
    carbs_g: 40,
    fat_g: 10,
    iron_mg: 1.8,
    calcium_mg: 30,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Roti',
    name_hindi: 'रोटी',
    aliases: ['chapati', 'phulka', 'wheat roti'],
    category: 'grain',
    cuisine_tag: 'north-indian',
    serving_unit: '1 medium',
    serving_size_grams: 35,
    calories: 85,
    protein_g: 2.7,
    carbs_g: 16,
    iron_mg: 1.1,
    calcium_mg: 10,
    fiber_g: 2.3,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Sabudana khichdi',
    name_hindi: 'साबूदाना खिचड़ी',
    aliases: ['sago khichdi', 'tapioca khichdi'],
    category: 'grain',
    cuisine_tag: 'maharashtrian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 220,
    protein_g: 2.5,
    carbs_g: 45,
    fat_g: 5,
    iron_mg: 1,
    calcium_mg: 15,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Thepla',
    name_hindi: 'थेपला',
    aliases: ['methi thepla', 'gujarati thepla'],
    category: 'grain',
    cuisine_tag: 'gujarati',
    serving_unit: '1 piece',
    serving_size_grams: 50,
    calories: 130,
    protein_g: 3.5,
    carbs_g: 18,
    fat_g: 5,
    iron_mg: 1.5,
    calcium_mg: 40,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Dhokla',
    name_hindi: 'ढोकला',
    aliases: ['khaman dhokla', 'besan dhokla'],
    category: 'grain',
    cuisine_tag: 'gujarati',
    serving_unit: '2 pieces',
    serving_size_grams: 80,
    calories: 155,
    protein_g: 5,
    carbs_g: 25,
    iron_mg: 1,
    calcium_mg: 25,
    pregnancy_safe: 'safe',
    is_verified: true,
  },

  // ── DALS & LEGUMES ─────────────────────────────────────────────────────────
  {
    name_english: 'Dal tadka',
    name_hindi: 'दाल तड़का',
    aliases: ['toor dal', 'arhar dal', 'yellow dal'],
    category: 'dal',
    cuisine_tag: 'north-indian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 130,
    protein_g: 8,
    carbs_g: 18,
    iron_mg: 3,
    calcium_mg: 30,
    folate_mcg: 45,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Excellent iron + folate source. Add tomato for vitamin C boost',
    is_verified: true,
  },
  {
    name_english: 'Rajma',
    name_hindi: 'राजमा',
    aliases: ['kidney beans', 'rajma chawal'],
    category: 'dal',
    cuisine_tag: 'punjabi',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 180,
    protein_g: 10,
    carbs_g: 32,
    iron_mg: 4.5,
    calcium_mg: 50,
    folate_mcg: 80,
    fiber_g: 8,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'High protein + iron + folate — pregnancy superfood',
    is_verified: true,
  },
  {
    name_english: 'Chana masala',
    name_hindi: 'छोले मसाला',
    aliases: ['chole', 'chickpea curry', 'chhole'],
    category: 'dal',
    cuisine_tag: 'punjabi',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 210,
    protein_g: 10.5,
    carbs_g: 35,
    iron_mg: 4,
    calcium_mg: 55,
    folate_mcg: 100,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Moong dal',
    name_hindi: 'मूंग दाल',
    aliases: ['yellow moong dal', 'green moong dal', 'mung dal'],
    category: 'dal',
    cuisine_tag: 'north-indian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 105,
    protein_g: 7,
    carbs_g: 18,
    iron_mg: 2.5,
    calcium_mg: 30,
    folate_mcg: 60,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Masoor dal',
    name_hindi: 'मसूर दाल',
    aliases: ['red lentil dal', 'pink lentils'],
    category: 'dal',
    cuisine_tag: 'north-indian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 115,
    protein_g: 8,
    carbs_g: 20,
    iron_mg: 3.5,
    calcium_mg: 25,
    folate_mcg: 70,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Chana dal',
    name_hindi: 'चना दाल',
    aliases: ['split chickpea dal', 'bengal gram dal'],
    category: 'dal',
    cuisine_tag: 'north-indian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 155,
    protein_g: 9,
    carbs_g: 28,
    iron_mg: 3,
    calcium_mg: 35,
    folate_mcg: 65,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Sprouts',
    name_hindi: 'अंकुरित दालें',
    aliases: ['mixed sprouts', 'moong sprouts', 'bean sprouts'],
    category: 'dal',
    serving_unit: '1 katori',
    serving_size_grams: 100,
    calories: 60,
    protein_g: 5,
    carbs_g: 9,
    iron_mg: 1.5,
    calcium_mg: 20,
    folate_mcg: 80,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Raw sprouts may carry bacteria — prefer lightly sauteed during pregnancy',
    is_verified: true,
  },

  // ── VEGETABLES ─────────────────────────────────────────────────────────────
  {
    name_english: 'Palak sabzi',
    name_hindi: 'पालक की सब्जी',
    aliases: ['spinach curry', 'palak', 'spinach sabzi'],
    category: 'vegetable',
    serving_unit: '1 katori',
    serving_size_grams: 100,
    calories: 65,
    protein_g: 3.5,
    iron_mg: 3.5,
    calcium_mg: 100,
    folate_mcg: 55,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Best iron source in vegetables. Pair with lemon/amla for absorption',
    is_verified: true,
  },
  {
    name_english: 'Bhindi sabzi',
    name_hindi: 'भिंडी की सब्जी',
    aliases: ['okra', 'lady finger', 'bhindi'],
    category: 'vegetable',
    serving_unit: '1 katori',
    serving_size_grams: 100,
    calories: 55,
    protein_g: 1.8,
    iron_mg: 0.6,
    calcium_mg: 66,
    folate_mcg: 88,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Lauki sabzi',
    name_hindi: 'लौकी की सब्जी',
    aliases: ['bottle gourd', 'ghiya', 'dudhi sabzi'],
    category: 'vegetable',
    serving_unit: '1 katori',
    serving_size_grams: 100,
    calories: 18,
    protein_g: 0.5,
    iron_mg: 0.3,
    calcium_mg: 26,
    hydration_per_serving_ml: 90,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Excellent hydration food, good for reducing swelling',
    is_verified: true,
  },
  {
    name_english: 'Aloo matar',
    name_hindi: 'आलू मटर',
    aliases: ['potato peas curry', 'matar aloo'],
    category: 'vegetable',
    cuisine_tag: 'north-indian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 160,
    protein_g: 5,
    carbs_g: 28,
    iron_mg: 2,
    calcium_mg: 30,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Baingan bharta',
    name_hindi: 'बैंगन का भर्ता',
    aliases: ['roasted eggplant', 'eggplant bharta', 'brinjal bharta'],
    category: 'vegetable',
    cuisine_tag: 'punjabi',
    serving_unit: '1 katori',
    serving_size_grams: 100,
    calories: 70,
    protein_g: 2,
    iron_mg: 0.5,
    calcium_mg: 20,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Mixed vegetable sabzi',
    name_hindi: 'मिक्स सब्जी',
    aliases: ['mix veg', 'sabzi', 'vegetable curry'],
    category: 'vegetable',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 110,
    protein_g: 3,
    iron_mg: 1.5,
    calcium_mg: 60,
    folate_mcg: 40,
    pregnancy_safe: 'safe',
    is_verified: true,
  },

  // ── DAIRY ──────────────────────────────────────────────────────────────────
  {
    name_english: 'Paneer',
    name_hindi: 'पनीर',
    aliases: ['cottage cheese', 'Indian cheese'],
    category: 'dairy',
    serving_unit: '100g',
    serving_size_grams: 100,
    calories: 265,
    protein_g: 18,
    fat_g: 20,
    calcium_mg: 480,
    b12_mcg: 0.3,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Best calcium + protein source for vegetarians',
    is_verified: true,
  },
  {
    name_english: 'Paneer bhurji',
    name_hindi: 'पनीर भुर्जी',
    aliases: ['scrambled paneer', 'paneer masala'],
    category: 'dairy',
    cuisine_tag: 'north-indian',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 320,
    protein_g: 20,
    fat_g: 24,
    calcium_mg: 520,
    iron_mg: 1.5,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Dahi',
    name_hindi: 'दही',
    aliases: ['curd', 'yogurt', 'plain yogurt'],
    category: 'dairy',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 85,
    protein_g: 4.5,
    fat_g: 4,
    calcium_mg: 150,
    b12_mcg: 0.5,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Probiotic — helps digestion and gut health',
    is_verified: true,
  },
  {
    name_english: 'Milk full fat',
    name_hindi: 'पूरा दूध',
    aliases: ['whole milk', 'gaay ka doodh', 'full cream milk'],
    category: 'dairy',
    serving_unit: '1 glass (200ml)',
    serving_size_grams: 206,
    calories: 130,
    protein_g: 6.8,
    fat_g: 7,
    calcium_mg: 240,
    b12_mcg: 0.9,
    vitamin_d_iu: 50,
    hydration_per_serving_ml: 175,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Lassi sweet',
    name_hindi: 'मीठी लस्सी',
    aliases: ['sweet lassi', 'dahi lassi'],
    category: 'dairy',
    cuisine_tag: 'punjabi',
    serving_unit: '1 glass (200ml)',
    serving_size_grams: 210,
    calories: 140,
    protein_g: 5,
    calcium_mg: 190,
    hydration_per_serving_ml: 170,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Chaas',
    name_hindi: 'छाछ',
    aliases: ['buttermilk', 'mattha', 'takra'],
    category: 'dairy',
    serving_unit: '1 glass (200ml)',
    serving_size_grams: 206,
    calories: 50,
    protein_g: 2,
    calcium_mg: 100,
    hydration_per_serving_ml: 200,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Kheer',
    name_hindi: 'खीर',
    aliases: ['rice kheer', 'payasam', 'rice pudding'],
    category: 'dairy',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 230,
    protein_g: 6,
    calcium_mg: 200,
    pregnancy_safe: 'safe',
    is_verified: true,
  },

  // ── RICE DISHES ────────────────────────────────────────────────────────────
  {
    name_english: 'Plain rice',
    name_hindi: 'सादा चावल',
    aliases: ['boiled rice', 'steamed rice', 'chawal'],
    category: 'grain',
    serving_unit: '1 katori cooked',
    serving_size_grams: 150,
    calories: 195,
    protein_g: 3.5,
    carbs_g: 43,
    iron_mg: 0.8,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Khichdi',
    name_hindi: 'खिचड़ी',
    aliases: ['dal khichdi', 'moong khichdi', 'rice lentil porridge'],
    category: 'grain',
    serving_unit: '1 katori',
    serving_size_grams: 200,
    calories: 210,
    protein_g: 8,
    carbs_g: 38,
    iron_mg: 2,
    calcium_mg: 30,
    folate_mcg: 25,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Easily digestible — ideal for T1 nausea and T3 digestion issues',
    trimester_notes: {
      T1: 'Ideal during nausea — easy on the stomach',
      T3: 'Good for digestion as baby grows and stomach space reduces',
    },
    is_verified: true,
  },
  {
    name_english: 'Curd rice',
    name_hindi: 'दही चावल',
    aliases: ['thayir sadam', 'yogurt rice', 'curd chawal'],
    category: 'grain',
    cuisine_tag: 'south-indian',
    serving_unit: '1 katori',
    serving_size_grams: 200,
    calories: 195,
    protein_g: 6,
    calcium_mg: 160,
    b12_mcg: 0.4,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Vegetable pulao',
    name_hindi: 'सब्जी पुलाव',
    aliases: ['veg pulao', 'vegetable rice', 'pilaf'],
    category: 'grain',
    serving_unit: '1 katori',
    serving_size_grams: 200,
    calories: 280,
    protein_g: 6,
    iron_mg: 1.5,
    calcium_mg: 40,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Veg biryani',
    name_hindi: 'वेज बिरयानी',
    aliases: ['vegetable biryani', 'veg dum biryani'],
    category: 'grain',
    cuisine_tag: 'hyderabadi',
    serving_unit: '1 plate',
    serving_size_grams: 300,
    calories: 420,
    protein_g: 9,
    iron_mg: 2.5,
    calcium_mg: 60,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Chicken biryani',
    name_hindi: 'चिकन बिरयानी',
    aliases: ['dum biryani chicken', 'murgh biryani'],
    category: 'grain',
    cuisine_tag: 'hyderabadi',
    serving_unit: '1 plate',
    serving_size_grams: 350,
    calories: 520,
    protein_g: 32,
    fat_g: 18,
    iron_mg: 3,
    calcium_mg: 50,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Ensure chicken is fully cooked — no pink inside',
    is_verified: true,
  },

  // ── NON-VEG ────────────────────────────────────────────────────────────────
  {
    name_english: 'Chicken curry',
    name_hindi: 'चिकन करी',
    aliases: ['murgh curry', 'chicken masala', 'chicken gravy'],
    category: 'non-veg',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 280,
    protein_g: 28,
    fat_g: 16,
    iron_mg: 1.5,
    calcium_mg: 20,
    b12_mcg: 0.6,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Ensure fully cooked — no pink inside',
    is_verified: true,
  },
  {
    name_english: 'Egg bhurji',
    name_hindi: 'अंडा भुर्जी',
    aliases: ['scrambled eggs', 'anda bhurji'],
    category: 'non-veg',
    serving_unit: '2 eggs',
    serving_size_grams: 120,
    calories: 185,
    protein_g: 13,
    fat_g: 14,
    iron_mg: 2,
    calcium_mg: 55,
    b12_mcg: 1.2,
    choline_mg: 250,
    vitamin_d_iu: 80,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Eggs are excellent for choline — crucial for baby brain development',
    is_verified: true,
  },
  {
    name_english: 'Boiled egg',
    name_hindi: 'उबला अंडा',
    aliases: ['hard boiled egg', 'anda', 'egg'],
    category: 'non-veg',
    serving_unit: '1 egg',
    serving_size_grams: 50,
    calories: 77,
    protein_g: 6.3,
    fat_g: 5.3,
    iron_mg: 0.9,
    calcium_mg: 25,
    b12_mcg: 0.6,
    choline_mg: 125,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Fish curry',
    name_hindi: 'मछली करी',
    aliases: ['fish gravy', 'machli curry', 'fish masala'],
    category: 'non-veg',
    serving_unit: '1 katori',
    serving_size_grams: 150,
    calories: 185,
    protein_g: 22,
    fat_g: 9,
    iron_mg: 1.5,
    calcium_mg: 45,
    omega3_mg: 800,
    dha_mg: 400,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Excellent DHA source for baby brain. Choose low-mercury fish like rohu, catla, pomfret',
    is_verified: true,
  },
  {
    name_english: 'Rawas / Indian Salmon',
    name_hindi: 'रावस',
    aliases: ['salmon', 'rawas fish', 'indian salmon'],
    category: 'non-veg',
    serving_unit: '100g',
    serving_size_grams: 100,
    calories: 208,
    protein_g: 20,
    fat_g: 13,
    dha_mg: 1200,
    omega3_mg: 2200,
    b12_mcg: 3.2,
    vitamin_d_iu: 570,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Best DHA + B12 + Vitamin D source. Excellent for baby brain and bone development',
    is_verified: true,
  },

  // ── FRUITS ─────────────────────────────────────────────────────────────────
  {
    name_english: 'Banana',
    name_hindi: 'केला',
    aliases: ['kela', 'plantain'],
    category: 'fruit',
    serving_unit: '1 medium',
    serving_size_grams: 120,
    calories: 105,
    protein_g: 1.3,
    carbs_g: 27,
    potassium_mg: 422,
    folate_mcg: 23,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'High potassium reduces leg cramps. Good energy source',
    is_verified: true,
  },
  {
    name_english: 'Apple',
    name_hindi: 'सेब',
    aliases: ['seb', 'red apple', 'green apple'],
    category: 'fruit',
    serving_unit: '1 medium',
    serving_size_grams: 150,
    calories: 78,
    fiber_g: 3.5,
    calcium_mg: 10,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Pomegranate',
    name_hindi: 'अनार',
    aliases: ['anar', 'pomegranate seeds', 'pomegranate arils'],
    category: 'fruit',
    serving_unit: '1 katori arils',
    serving_size_grams: 150,
    calories: 105,
    protein_g: 1.5,
    iron_mg: 0.5,
    folate_mcg: 38,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Rich in antioxidants and folate',
    is_verified: true,
  },
  {
    name_english: 'Dates',
    name_hindi: 'खजूर',
    aliases: ['khajoor', 'medjool dates', 'dried dates'],
    category: 'fruit',
    serving_unit: '4 pieces',
    serving_size_grams: 40,
    calories: 112,
    iron_mg: 0.9,
    calcium_mg: 16,
    folate_mcg: 7,
    potassium_mg: 330,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Natural energy + iron. Traditionally given in T3 to ease labor',
    trimester_notes: { T3: 'Studies suggest daily dates from week 36 may ease labor' },
    is_verified: true,
  },
  {
    name_english: 'Orange',
    name_hindi: 'संतरा',
    aliases: ['santra', 'sweet lime', 'citrus'],
    category: 'fruit',
    serving_unit: '1 medium',
    serving_size_grams: 150,
    calories: 62,
    folate_mcg: 40,
    calcium_mg: 52,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Excellent with iron-rich meals — vitamin C doubles iron absorption',
    is_verified: true,
  },
  {
    name_english: 'Ripe papaya',
    name_hindi: 'पका पपीता',
    aliases: ['papaya', 'papita ripe'],
    category: 'fruit',
    serving_unit: '1 slice',
    serving_size_grams: 100,
    calories: 43,
    folate_mcg: 37,
    pregnancy_safe: 'moderate',
    pregnancy_notes: 'RIPE papaya in small amounts is fine. RAW/unripe papaya MUST be avoided — contains papain which may trigger contractions',
    trimester_notes: {
      T1: 'Avoid completely in T1 — even ripe papaya carries risk in first trimester',
      T2: 'Small amounts of fully ripe papaya are acceptable',
      T3: 'Small amounts of fully ripe papaya are acceptable',
    },
    is_verified: true,
  },
  {
    name_english: 'Anjeer',
    name_hindi: 'अंजीर',
    aliases: ['fig', 'dried fig', 'fresh fig'],
    category: 'fruit',
    serving_unit: '3 pieces',
    serving_size_grams: 60,
    calories: 148,
    calcium_mg: 95,
    iron_mg: 1.1,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Amla',
    name_hindi: 'आंवला',
    aliases: ['indian gooseberry', 'amla berry', 'nelli'],
    category: 'fruit',
    serving_unit: '2 pieces',
    serving_size_grams: 50,
    calories: 22,
    calcium_mg: 25,
    iron_mg: 1.2,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Highest vitamin C food — superb iron absorption booster',
    is_verified: true,
  },
  {
    name_english: 'Chikoo',
    name_hindi: 'चीकू',
    aliases: ['sapota', 'sapodilla', 'naseberry'],
    category: 'fruit',
    serving_unit: '1 medium',
    serving_size_grams: 100,
    calories: 83,
    calcium_mg: 21,
    iron_mg: 0.8,
    pregnancy_safe: 'safe',
    is_verified: true,
  },

  // ── BEVERAGES ──────────────────────────────────────────────────────────────
  {
    name_english: 'Coconut water',
    name_hindi: 'नारियल पानी',
    aliases: ['nariyal pani', 'tender coconut water'],
    category: 'beverage',
    serving_unit: '1 glass (200ml)',
    serving_size_grams: 200,
    calories: 38,
    potassium_mg: 400,
    calcium_mg: 24,
    hydration_per_serving_ml: 200,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Excellent electrolyte drink — reduces swelling and nausea',
    is_verified: true,
  },
  {
    name_english: 'Chai with milk',
    name_hindi: 'चाय',
    aliases: ['tea with milk', 'masala chai', 'indian tea'],
    category: 'beverage',
    serving_unit: '1 cup (150ml)',
    serving_size_grams: 155,
    calories: 55,
    calcium_mg: 60,
    hydration_per_serving_ml: 100,
    pregnancy_safe: 'moderate',
    pregnancy_notes: 'Limit to 1-2 cups/day. Each cup has ~25mg caffeine. Over 200mg caffeine/day is not recommended',
    is_verified: true,
  },
  {
    name_english: 'Coffee',
    name_hindi: 'कॉफ़ी',
    aliases: ['filter coffee', 'instant coffee', 'black coffee'],
    category: 'beverage',
    serving_unit: '1 cup (150ml)',
    serving_size_grams: 155,
    calories: 10,
    hydration_per_serving_ml: 100,
    pregnancy_safe: 'moderate',
    pregnancy_notes: 'High caffeine — limit strictly. 1 small cup/day max. Avoid in T1 if possible',
    trimester_notes: { T1: 'Avoid completely in T1 — caffeine most harmful to embryo development' },
    is_verified: true,
  },
  {
    name_english: 'Nimbu pani',
    name_hindi: 'नींबू पानी',
    aliases: ['lemon water', 'lemonade', 'shikanji'],
    category: 'beverage',
    serving_unit: '1 glass (200ml)',
    serving_size_grams: 200,
    calories: 25,
    hydration_per_serving_ml: 200,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Great hydration + vitamin C. Use black salt for electrolytes',
    is_verified: true,
  },
  {
    name_english: 'Banana milkshake',
    name_hindi: 'केला मिल्कशेक',
    aliases: ['banana shake', 'kela shake'],
    category: 'beverage',
    serving_unit: '1 glass (250ml)',
    serving_size_grams: 260,
    calories: 185,
    protein_g: 5,
    calcium_mg: 180,
    potassium_mg: 500,
    hydration_per_serving_ml: 200,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Warm milk with haldi',
    name_hindi: 'हल्दी वाला दूध',
    aliases: ['golden milk', 'turmeric milk', 'haldi doodh'],
    category: 'beverage',
    serving_unit: '1 glass (200ml)',
    serving_size_grams: 206,
    calories: 140,
    protein_g: 7,
    calcium_mg: 250,
    b12_mcg: 0.9,
    hydration_per_serving_ml: 175,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Anti-inflammatory. Excellent calcium source before bed',
    is_verified: true,
  },
  {
    name_english: 'Green tea',
    name_hindi: 'ग्रीन टी',
    aliases: ['green tea', 'herbal green tea'],
    category: 'beverage',
    serving_unit: '1 cup (150ml)',
    serving_size_grams: 150,
    calories: 2,
    hydration_per_serving_ml: 120,
    pregnancy_safe: 'moderate',
    pregnancy_notes: 'Contains some caffeine and tannins that reduce iron absorption. Avoid with meals. Max 1 cup/day',
    is_verified: true,
  },

  // ── SNACKS & SUPERFOODS ────────────────────────────────────────────────────
  {
    name_english: 'Makhana',
    name_hindi: 'मखाना',
    aliases: ['fox nuts', 'lotus seeds', 'phool makhana'],
    category: 'snack',
    serving_unit: '1 handful',
    serving_size_grams: 30,
    calories: 107,
    protein_g: 3.5,
    calcium_mg: 60,
    iron_mg: 1.4,
    magnesium_mg: 67,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Excellent pregnancy snack — low fat, high calcium and magnesium',
    is_verified: true,
  },
  {
    name_english: 'Mixed nuts',
    name_hindi: 'मिक्स नट्स',
    aliases: ['dry fruits', 'almonds cashews walnuts', 'mixed dry fruits'],
    category: 'snack',
    serving_unit: '1 small handful',
    serving_size_grams: 30,
    calories: 180,
    protein_g: 5,
    omega3_mg: 600,
    calcium_mg: 40,
    iron_mg: 1,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Til laddoo',
    name_hindi: 'तिल के लड्डू',
    aliases: ['sesame laddoo', 'til ke ladoo', 'sesame balls'],
    category: 'snack',
    cuisine_tag: 'north-indian',
    serving_unit: '1 piece',
    serving_size_grams: 30,
    calories: 145,
    calcium_mg: 200,
    iron_mg: 2.5,
    pregnancy_safe: 'moderate',
    pregnancy_notes: 'Highly nutritious but avoid large quantities in T1. 1-2 pieces in T2-T3 is fine',
    trimester_notes: { T1: 'Avoid in T1 — sesame in large amounts has uterine stimulating properties' },
    is_verified: true,
  },
  {
    name_english: 'Protein laddoo',
    name_hindi: 'प्रोटीन लड्डू',
    aliases: ['energy laddoo', 'nut laddoo', 'dry fruit laddoo'],
    category: 'snack',
    serving_unit: '1 piece',
    serving_size_grams: 40,
    calories: 165,
    protein_g: 8,
    calcium_mg: 80,
    iron_mg: 2,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Peanuts',
    name_hindi: 'मूंगफली',
    aliases: ['groundnuts', 'moongfali', 'roasted peanuts'],
    category: 'snack',
    serving_unit: '1 handful',
    serving_size_grams: 30,
    calories: 170,
    protein_g: 7.5,
    folate_mcg: 27,
    iron_mg: 1.3,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'High protein snack. Check for nut allergy history',
    is_verified: true,
  },
  {
    name_english: 'Khakra',
    name_hindi: 'खाखरा',
    aliases: ['khakhra', 'gujarati khakra'],
    category: 'snack',
    cuisine_tag: 'gujarati',
    serving_unit: '2 pieces',
    serving_size_grams: 40,
    calories: 155,
    protein_g: 4,
    iron_mg: 1.5,
    calcium_mg: 20,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Rusk',
    name_hindi: 'रस्क',
    aliases: ['toast rusk', 'bread rusk'],
    category: 'snack',
    serving_unit: '2 pieces',
    serving_size_grams: 40,
    calories: 160,
    protein_g: 3.5,
    calcium_mg: 15,
    pregnancy_safe: 'safe',
    is_verified: true,
  },

  // ── SPECIAL PREGNANCY FOODS ────────────────────────────────────────────────
  {
    name_english: 'Moringa sabzi',
    name_hindi: 'सहजन की सब्जी',
    aliases: ['drumstick leaves', 'moringa leaves', 'sahjan ki sabzi'],
    category: 'vegetable',
    serving_unit: '1 katori',
    serving_size_grams: 80,
    calories: 55,
    protein_g: 4,
    iron_mg: 4,
    calcium_mg: 185,
    folate_mcg: 40,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Nutritional powerhouse — very high iron and calcium',
    is_verified: true,
  },
  {
    name_english: 'Methi sabzi',
    name_hindi: 'मेथी की सब्जी',
    aliases: ['fenugreek leaves', 'methi', 'fenugreek sabzi'],
    category: 'vegetable',
    serving_unit: '1 katori',
    serving_size_grams: 100,
    calories: 49,
    iron_mg: 2.5,
    calcium_mg: 176,
    folate_mcg: 57,
    pregnancy_safe: 'moderate',
    pregnancy_notes: 'Excellent nutrients but large amounts may stimulate contractions. Small culinary amounts are fine',
    trimester_notes: { T1: 'Use in very small amounts only — avoid methi seeds in T1' },
    is_verified: true,
  },
  {
    name_english: 'Bajra roti',
    name_hindi: 'बाजरे की रोटी',
    aliases: ['pearl millet roti', 'bajra chapati', 'millet roti'],
    category: 'grain',
    cuisine_tag: 'rajasthani',
    serving_unit: '1 roti',
    serving_size_grams: 40,
    calories: 118,
    protein_g: 3.5,
    iron_mg: 3,
    calcium_mg: 19,
    magnesium_mg: 45,
    fiber_g: 2,
    pregnancy_safe: 'safe',
    is_verified: true,
  },
  {
    name_english: 'Ragi dosa',
    name_hindi: 'रागी डोसा',
    aliases: ['nachni dosa', 'finger millet dosa', 'ragi uttapam'],
    category: 'grain',
    cuisine_tag: 'karnataka',
    serving_unit: '1 medium',
    serving_size_grams: 80,
    calories: 130,
    protein_g: 3,
    calcium_mg: 144,
    iron_mg: 3.9,
    pregnancy_safe: 'safe',
    pregnancy_notes: 'Highest calcium grain — excellent for vegetarians',
    is_verified: true,
  },
  {
    name_english: 'Saag',
    name_hindi: 'साग',
    aliases: ['mustard greens', 'sarson ka saag', 'mustard leaf curry'],
    category: 'vegetable',
    cuisine_tag: 'punjabi',
    serving_unit: '1 katori',
    serving_size_grams: 100,
    calories: 45,
    protein_g: 3.5,
    iron_mg: 1.5,
    calcium_mg: 155,
    folate_mcg: 45,
    pregnancy_safe: 'safe',
    is_verified: true,
  },

  // ── AVOID / UNSAFE FOODS ───────────────────────────────────────────────────
  {
    name_english: 'Raw papaya',
    name_hindi: 'कच्चा पपीता',
    aliases: ['unripe papaya', 'green papaya', 'raw papita'],
    category: 'fruit',
    serving_unit: '1 serving',
    serving_size_grams: 100,
    calories: 32,
    pregnancy_safe: 'avoid',
    pregnancy_notes: 'Contains papain enzyme — can trigger uterine contractions. Strictly avoid throughout pregnancy',
    is_verified: true,
  },
  {
    name_english: 'Pineapple juice large',
    name_hindi: 'अनानास का रस',
    aliases: ['pineapple juice', 'ananas juice', 'pineapple'],
    category: 'beverage',
    serving_unit: '1 large glass',
    serving_size_grams: 300,
    calories: 132,
    pregnancy_safe: 'avoid',
    pregnancy_notes: 'Large quantities contain bromelain — avoid in T1 especially. Small portions of fresh pineapple are okay',
    trimester_notes: { T1: 'Strictly avoid in T1 — bromelain can soften the cervix' },
    is_verified: true,
  },
  {
    name_english: 'Unpasteurized paneer',
    name_hindi: 'कच्चा पनीर (अनपाश्चुरीकृत)',
    aliases: ['raw milk paneer', 'desi paneer unpasteurized'],
    category: 'dairy',
    serving_unit: '100g',
    serving_size_grams: 100,
    calories: 265,
    pregnancy_safe: 'avoid',
    pregnancy_notes: 'Risk of listeria infection — use only pasteurized dairy products during pregnancy',
    is_verified: true,
  },
  {
    name_english: 'Raw fish / Sushi',
    name_hindi: 'कच्ची मछली',
    aliases: ['sushi', 'sashimi', 'raw seafood', 'raw fish'],
    category: 'non-veg',
    serving_unit: '1 serving',
    serving_size_grams: 100,
    calories: 150,
    pregnancy_safe: 'avoid',
    pregnancy_notes: 'Risk of mercury and bacterial contamination — all fish must be fully cooked during pregnancy',
    is_verified: true,
  },
  {
    name_english: 'Liver',
    name_hindi: 'कलेजी',
    aliases: ['chicken liver', 'mutton liver', 'kaleji'],
    category: 'non-veg',
    serving_unit: '1 serving',
    serving_size_grams: 100,
    calories: 165,
    protein_g: 26,
    iron_mg: 6.5,
    b12_mcg: 70,
    pregnancy_safe: 'moderate',
    pregnancy_notes: 'Very high vitamin A in large amounts can cause birth defects. Small amounts occasionally fine — max once a month',
    is_verified: true,
  },
  {
    name_english: 'Alcohol',
    name_hindi: 'शराब',
    aliases: ['wine', 'beer', 'spirits', 'liquor', 'sharab'],
    category: 'beverage',
    serving_unit: '1 drink',
    serving_size_grams: 150,
    calories: 120,
    pregnancy_safe: 'avoid',
    pregnancy_notes: 'No safe amount of alcohol during pregnancy — causes fetal alcohol syndrome',
    is_verified: true,
  },
]

async function seed() {
  console.log('🌱 GarbhaMitra Food Database Seeder')
  console.log('─'.repeat(40))

  // Check if already seeded
  const { count, error: countError } = await supabase
    .from('food_items')
    .select('*', { count: 'exact', head: true })

  if (countError) {
    console.error('❌ Cannot connect to Supabase:', countError.message)
    console.error('   Check NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local')
    process.exit(1)
  }

  if (count && count > 0) {
    console.log(`✅ Food database already has ${count} items. Skipping seed.`)
    return
  }

  console.log(`📦 Inserting ${foodItems.length} food items in batches of 20...\n`)

  const batchSize = 20
  let totalInserted = 0

  for (let i = 0; i < foodItems.length; i += batchSize) {
    const batch = foodItems.slice(i, i + batchSize)
    const batchNum = Math.floor(i / batchSize) + 1

    const { error } = await supabase.from('food_items').insert(batch)

    if (error) {
      console.error(`❌ Batch ${batchNum} failed (items ${i + 1}–${i + batch.length}):`, error.message)
    } else {
      totalInserted += batch.length
      const names = batch.map(f => f.name_english).join(', ')
      console.log(`✅ Batch ${batchNum} (${batch.length} items): ${names}`)
    }
  }

  // Final count
  const { count: finalCount } = await supabase
    .from('food_items')
    .select('*', { count: 'exact', head: true })

  console.log('\n' + '─'.repeat(40))
  console.log(`🎉 Seed complete! Total food items in database: ${finalCount}`)
  console.log(`   Inserted: ${totalInserted} / ${foodItems.length}`)
}

seed().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
